In [124]:
import numpy as np
import copy


class State:
    # board
    # parent
    # g
    # h
    def __init__(self, board=None): # must be a numpy board

        if board == None:
            #print('here')
            boardUsingList = [
                              [7,2,4],
                              [5,0,6],
                              [8,3,1]
                            ]
            self.board = np.array(boardUsingList)
        else:
            self.board=board

        self.g=0
        self.h=0
        self.parent=None

    def printState(self):
        print("*******************")
        print(self.board)
        print("*******************")


    def moveUp(self):
        child = copy.deepcopy(self)
        r0,c0 = np.where(self.board==0)
        r0=r0[0]
        c0=c0[0]
        # print(r0)
        # print(c0)
        # print(self.board[r0][c0])

        rOther=r0-1
        cOther=c0

        if(rOther<0):
            return child

        child.board [r0][c0] = child.board [rOther][cOther]
        child.board [rOther][cOther] = 0
        #print('here')
        return child




    def moveDown(self):
        child = copy.deepcopy(self)
        r0,c0 = np.where(self.board==0)
        r0=r0[0]
        c0=c0[0]
        # print(r0)
        # print(c0)
        # print(self.board[r0][c0])

        rOther=r0+1
        cOther=c0

        if(rOther>2):
            return child

        child.board [r0][c0] = child.board [rOther][cOther]
        child.board [rOther][cOther] = 0
        #print('Here')
        return child

    def moveLeft(self):
        child = copy.deepcopy(self)
        r0,c0 = np.where(self.board==0)
        r0=r0[0]
        c0=c0[0]
        # print(r0)
        # print(c0)
        # print(self.board[r0][c0])

        rOther=r0
        cOther=c0-1

        #print(rOther)
        #print(cOther)

        if(cOther<0):
            #print('debug')
            return child

        child.board [r0][c0] = child.board [rOther][cOther]
        child.board [rOther][cOther] = 0
        #print('Here')
        return child


    def moveRight(self):
        child = copy.deepcopy(self)
        r0,c0 = np.where(self.board==0)
        r0=r0[0]
        c0=c0[0]
        # print(r0)
        # print(c0)
        # print(self.board[r0][c0])

        rOther=r0
        cOther=c0+1

        if(cOther>2):

            return child

        child.board [r0][c0] = child.board [rOther][cOther]
        child.board [rOther][cOther] = 0

        return child

    def __eq__(self,otherNode):
        if(otherNode==None):
            return False
        if(np.array_equal(self.board,otherNode.board)):
            return True
        else:
            return False
    def __hash__(self):
        return 1

In [125]:
state = State()
state.printState()

*******************
[[7 2 4]
 [5 0 6]
 [8 3 1]]
*******************


In [126]:
child1 = state.moveUp()
child1.printState()
child1 = state.moveDown()
child1.printState()
child1 = state.moveLeft()
child1.printState()
child1 = state.moveRight()
child1.printState()

*******************
[[7 0 4]
 [5 2 6]
 [8 3 1]]
*******************
*******************
[[7 2 4]
 [5 3 6]
 [8 0 1]]
*******************
*******************
[[7 2 4]
 [0 5 6]
 [8 3 1]]
*******************
*******************
[[7 2 4]
 [5 6 0]
 [8 3 1]]
*******************


In [127]:
def goalTest(node):
      goalBoardUsingList = [
                    [0,1,2],
                    [3,4,5],
                    [6,7,8]
                  ]
      goalBoard = np.array(goalBoardUsingList)

      if np.array_equal(node.board,goalBoard):
          return True
      else:
          return False

In [128]:
goalTest(state)

False

In [129]:
def calculateHeuristics(node):
      goalBoardUsingList = [
                    [0,1,2],
                    [3,4,5],
                    [6,7,8]
                  ]
      goalBoard = np.array(goalBoardUsingList)

      totalDistance = 0
      for i in range(1,9):
          ri,ci = np.where(node.board==i)
          ri=ri[0]
          ci=ci[0]

          rg,cg = np.where(goalBoard==i)
          rg=rg[0]
          cg=cg[0]

          dist = abs(ri-rg)+abs(ci-cg)
          totalDistance +=dist

      return totalDistance

In [130]:
state = State()
calculateHeuristics(state)

18

In [131]:
def sumOfGandH(node):
  return node.h-node.g

In [132]:
def a_star_search (initialNode):
    if goalTest(initialNode):
        return initialNode

    frontier = list() # queue
    explored = set()


    initialNode.g=0
    initialNode.h=calculateHeuristics(initialNode)
    frontier.append(initialNode)

    while True:
        if (len(frontier)==0):
            return None

        frontier.sort(key=sumOfGandH)
        node = frontier.pop(0)
        explored.add(node)
        print(len(frontier))

        actions = [node.moveUp,node.moveDown,node.moveLeft,node.moveRight]

        for action in actions:
            child = action()
            child.g=node.g+50
            child.h=calculateHeuristics(child)
            child.parent=node
            if (child not in frontier) and (child not in explored):
                if(goalTest(child)):
                    return child
                frontier.append(child)
            elif child in frontier:
                 indexOfChildInFrontier = frontier.index(child)
                 childInFrontier = frontier[indexOfChildInFrontier]
                 if(child.g+child.h<childInFrontier.g+childInFrontier.h):
                      frontier[indexOfChildInFrontier]=child
                      frontier.sort(key=sumOfGandH)

In [ ]:
state = State()
result = a_star_search(state)


In [134]:
def printSolution(state):
    if(state==None):
      return
    else:
      printSolution(state.parent)
      state.printState()

In [135]:
printSolution(result)

*******************
[[7 2 4]
 [5 0 6]
 [8 3 1]]
*******************
*******************
[[7 2 4]
 [5 3 6]
 [8 0 1]]
*******************
*******************
[[7 2 4]
 [5 3 6]
 [0 8 1]]
*******************
*******************
[[7 2 4]
 [0 3 6]
 [5 8 1]]
*******************
*******************
[[0 2 4]
 [7 3 6]
 [5 8 1]]
*******************
*******************
[[2 0 4]
 [7 3 6]
 [5 8 1]]
*******************
*******************
[[2 4 0]
 [7 3 6]
 [5 8 1]]
*******************
*******************
[[2 4 6]
 [7 3 0]
 [5 8 1]]
*******************
*******************
[[2 4 6]
 [7 3 1]
 [5 8 0]]
*******************
*******************
[[2 4 6]
 [7 3 1]
 [5 0 8]]
*******************
*******************
[[2 4 6]
 [7 3 1]
 [0 5 8]]
*******************
*******************
[[2 4 6]
 [0 3 1]
 [7 5 8]]
*******************
*******************
[[2 4 6]
 [3 0 1]
 [7 5 8]]
*******************
*******************
[[2 0 6]
 [3 4 1]
 [7 5 8]]
*******************
*******************
[[0 2 6]
 [3 4 1]
 [7 5 8]]
