In [4]:
import numpy as np
import pandas as pd

In [11]:
datasetPath = '/content/drive/MyDrive/Class Contents/5. Summer 2024/AI Lab/Class Materials For The Students/Week 5/knn_dataset.xlsx'

In [12]:
dataFrame = pd.read_excel(datasetPath)

In [13]:
print(dataFrame)

   Age  Rooms  Square Feet  Windows Label Meaning
0    5      3         1500        4          High
1   10      2         1200        3        Medium
2    3      4         1800        5          High
3    8      3         1300        4        Medium
4   15      2          900        2           Low
5    7      3         1400        3        Medium
6    2      5         2000        6          High
7    6      2         1100        3           Low
8   12      3         1600        4          High
9    4      4         1700        5        Medium


In [14]:
dataSet = dataFrame.to_numpy()

In [15]:
print(dataSet)

[[5 3 1500 4 'High']
 [10 2 1200 3 'Medium']
 [3 4 1800 5 'High']
 [8 3 1300 4 'Medium']
 [15 2 900 2 'Low']
 [7 3 1400 3 'Medium']
 [2 5 2000 6 'High']
 [6 2 1100 3 'Low']
 [12 3 1600 4 'High']
 [4 4 1700 5 'Medium']]


In [26]:
dataSet[np.where(dataSet=='High')] = 2
dataSet[np.where(dataSet=='Medium')] = 1
dataSet[np.where(dataSet=='Low')] = 0

In [27]:
print(dataSet)

[[5 3 1500 4 2]
 [10 2 1200 3 1]
 [3 4 1800 5 2]
 [8 3 1300 4 1]
 [15 2 900 2 0]
 [7 3 1400 3 1]
 [2 5 2000 6 2]
 [6 2 1100 3 0]
 [12 3 1600 4 2]
 [4 4 1700 5 1]]


In [29]:
x=dataSet[0:10,0:4]
print(x)

[[5 3 1500 4]
 [10 2 1200 3]
 [3 4 1800 5]
 [8 3 1300 4]
 [15 2 900 2]
 [7 3 1400 3]
 [2 5 2000 6]
 [6 2 1100 3]
 [12 3 1600 4]
 [4 4 1700 5]]


In [31]:
y=dataSet[0:10,4]
print(y)

[2 1 2 1 0 1 2 0 2 1]


In [32]:
x_test=np.asarray([4,3,1505,5])

In [34]:
def eucledianDistance(x1,x2):
    distance = (x1[0]-x2[0])**2+(x1[1]-x2[1])**2+(x1[2]-x2[2])**2+(x1[3]-x2[3])**2
    distance = distance**0.5
    return distance

In [ ]:
eucledianDistance(x[0],x_test)

In [45]:
distances=[]

for i in x:
    d = eucledianDistance(i,x_test)
    distances.append(d)

distances= np.asarray(distances)
print(distances)

[  5.19615242 305.06720571 295.00338981 205.04145922 605.10825478
 105.06188652 495.00909083 405.01111096  95.34149149 195.00256409]


In [49]:
k = 3
sortedDistances = np.argsort(distances)
print(sortedDistances)

[0 8 5 9 3 2 1 7 6 4]


In [52]:
sortedDistancs = sortedDistances[0:3]
print(sortedDistancs)

[0 8 5]


In [53]:
poll = dict()
poll[0]=0 # voting poll for low
poll[1]=0 # voting poll for medium
poll[2]=0 # voting poll for high

In [55]:
for i in sortedDistancs:
    label = y[i]
    poll[label]=poll[label]+1

In [59]:
result = max(poll)

if(result==0):
    print('Low rent')
elif(result==1):
    print('Medium rent')
else:
    print('High rent')

High rent
